language: php

sudo: required

dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer config discard-changes true
  - travis_retry composer install --prefer-dist --no-interaction
